using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;

namespace Sqlbi.PbiPushDataset
{
    /// <summary>
    /// Simulation type
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SimulationType
    {
        /// <summary>
        /// Always write the same value
        /// </summary>
        Fixed,

        /// <summary>
        /// Write a random element from a list of values
        /// </summary>
        List,

        /// <summary>
        /// Choose a random value in the provided range and granularity
        /// </summary>
        Range
    }

    /// <summary>
    /// Range of values for a numeric column in the simulation
    /// </summary>
    public class SimulationRange
    {
        /// <summary>
        /// Minimum value in the range
        /// </summary>
        public double Min { get; set; }

        /// <summary>
        /// Maximum value in the range
        /// </summary>
        public double Max { get; set; }

        /// <summary>
        /// Range granularity: use 0 for integers, 1 = 0.1, 2 = 0.01, -2 = multiple of 100
        /// </summary>
        public int Granularity { get; set; }
    }

    /// <summary>
    /// Column parameters for the simulation
    /// </summary>
    [JsonObject(ItemNullValueHandling = NullValueHandling.Ignore)]
    public class ColumnParameters
    {
        /// <summary>
        /// Column name
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Simulation type
        /// </summary>
        public SimulationType Type { get; set; }

        /// <summary>
        /// Range of values for the simulation
        /// </summary>
        public SimulationRange Range { get; set; }

        /// <summary>
        /// List of allowed values for the simulation
        /// </summary>
        public object[] AllowedValues { get; set; }

        /// <summary>
        /// Fixed value used in the simulation
        /// </summary>
        public object FixedValue { get; set; }

        private readonly Random rnd = new Random();

        /// <summary>
        /// Generates the value for the column during a simulation 
        /// based on the configuration for this instance
        /// </summary>
        /// <returns></returns>
        public object GenerateValue()
        {
            return Type switch
            {
                SimulationType.Fixed => FixedValue,
                SimulationType.List => AllowedValues[rnd.Next(0, AllowedValues.Length)],
                SimulationType.Range => 
                    (Range.Granularity == 0) 
                        ? rnd.Next((int)Range.Min,(int)Range.Max)
                        : (Range.Granularity > 0)
                            ? Math.Round(Range.Min + (rnd.NextDouble() * (Range.Min - Range.Max)), Range.Granularity)
                            : (int)(Math.Pow(10, -Range.Granularity) * (Range.Min + (rnd.NextDouble() * (Range.Min - Range.Max))) ),
                _ => throw new ArgumentException("Simulation Type not defined."),
            };
        }
    }

    /// <summary>
    /// Table parameters for the simulation
    /// </summary>
    public class TableParameters
    {
        /// <summary>
        /// Table name
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Number of rows in each batch
        /// </summary>
        public long BatchRows { get; set; }

        /// <summary>
        /// Simulation parameters for the columns of the table
        /// The array contains only the columns generated by the simulator,
        /// the other columns are left blank
        /// </summary>
        public ColumnParameters[] Columns { get; set; }

        /// <summary>
        /// Generates a row during the simulation
        /// </summary>
        /// <returns>Generated row</returns>
        public System.Dynamic.ExpandoObject GenerateRow()
        {
            var row = new System.Dynamic.ExpandoObject();
            foreach (var column in Columns)
            {
                row.TryAdd(column.Name, column.GenerateValue());
            }
            return row;
        }
    }

    /// <summary>
    /// Parameters for the simulation
    /// </summary>
    public class SimulationParameters
    {
        /// <summary>
        /// Interval between two batches (seconds)
        /// </summary>
        public long BatchInterval { get; set; }

        /// <summary>
        /// Tables involved in the simulation
        /// </summary>
        public TableParameters[] Tables {get; set;}

    }

    public class Simulator
    {
        /// <summary>
        /// Parameters for the simulator
        /// </summary>
        public SimulationParameters Parameters { get; set; }

        public static Simulator ReadParameters(string path)
        {
            string s = System.IO.File.ReadAllText(path);
            Simulator simulator = new Simulator
            {
                Parameters = JsonConvert.DeserializeObject<SimulationParameters>(s)
            };
            return simulator;
        }

        public void WriteParameters( string path )
        {
            string s = JsonConvert.SerializeObject(Parameters, new JsonSerializerSettings { ContractResolver = new CamelCasePropertyNamesContractResolver() });
            System.IO.File.WriteAllText(path, s);
        }
    }
}
